# Generated by Django 5.2.17 on 2026-08-19 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('x_twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook')], max_length=32)),
                ('account_handle', models.CharField(max_length=128)),
                ('account_id', models.CharField(blank=True, help_text='Platform-specific external entity ID (e.g. Page ID, IG User ID, TikTok Open ID)', max_length=128, null=True)),
                ('client_id', models.CharField(blank=True, help_text='Public Client Key / App ID / Client ID for OAuth', max_length=128, null=True)),
                ('token_type', models.CharField(default='bearer', help_text="Token type: 'bearer', 'page_token', 'user_token', etc.", max_length=32)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Authorized OAuth permission scopes')),
                ('encrypted_access_token', models.TextField(help_text='Encrypted OAuth2 Bearer Token')),
                ('encrypted_refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_remaining', models.IntegerField(default=100)),
                ('rate_limit_reset_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Account',
                'verbose_name_plural': 'Platform Accounts',
                'indexes': [
                    models.Index(fields=['platform', 'account_handle'], name='social_agen_platfor_e5f80b_idx'),
                    models.Index(fields=['platform', 'is_active'], name='social_agen_platfor_28741e_idx'),
                ],
                'unique_together': {('platform', 'account_handle')},
            },
        ),
        migrations.CreateModel(
            name='SocialCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('raw_prompt', models.TextField(help_text='Original campaign objective or prompt')),
                ('target_platforms', models.JSONField(default=list, help_text="List of platforms: ['x_twitter', 'instagram', 'tiktok', 'facebook']")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Execution'), ('RUNNING', 'Running In Graph'), ('AWAITING_APPROVAL', 'Awaiting Human Approval (HITL)'), ('APPROVED', 'Approved by Human'), ('REJECTED', 'Rejected by Human'), ('PUBLISHED', 'Published to Platforms'), ('FAILED', 'Failed / Fatal Error')], default='PENDING', max_length=32)),
                ('langgraph_thread_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('current_checkpoint_id', models.CharField(blank=True, max_length=128, null=True)),
                ('overall_quality_score', models.FloatField(default=0.0)),
                ('safety_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Campaign',
                'verbose_name_plural': 'Social Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=64)),
                ('agent_name', models.CharField(max_length=64)),
                ('input_state_summary', models.TextField()),
                ('output_state_summary', models.TextField()),
                ('evaluation_rubric', models.JSONField(blank=True, default=dict)),
                ('execution_time_seconds', models.FloatField(default=0.0)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='social_agent.socialcampaign')),
            ],
            options={
                'verbose_name': 'Agent Audit Log',
                'verbose_name_plural': 'Agent Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=32)),
                ('post_text', models.TextField()),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('alt_text', models.TextField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, max_length=128, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('character_count', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social_agent.socialcampaign')),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
            },
        ),
    ]
