# Generated by Django 6.0.5 on 2026-08-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformaccount',
            new_name='social_agen_platfor_eda991_idx',
            old_name='social_agen_platfor_e5f80b_idx',
        ),
        migrations.RenameIndex(
            model_name='platformaccount',
            new_name='social_agen_platfor_0f5361_idx',
            old_name='social_agen_platfor_28741e_idx',
        ),
    ]
