# Generated by Django 6.0.5 on 2026-08-20 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_agent', '0002_rename_social_agen_platfor_e5f80b_idx_social_agen_platfor_eda991_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_role', models.CharField(choices=[('researcher', 'Trend Researcher'), ('copywriter', 'Copywriter'), ('media_specialist', 'Media Specialist'), ('auditor', 'Compliance Auditor'), ('publisher', 'Social Publisher')], max_length=32, unique=True)),
                ('model_name', models.CharField(default='llama3.3:70b-instruct', max_length=128)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('endpoint_url', models.URLField(blank=True, help_text='Custom LLM API Endpoint', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configurations',
            },
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key or Client ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='api_secret',
            field=models.CharField(blank=True, help_text='API Secret or Client Secret', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Webhook validation secret', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='encrypted_access_token',
            field=models.TextField(blank=True, help_text='Encrypted OAuth2 Bearer Token', null=True),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='encrypted_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
