# Generated by Django 6.0.5 on 2026-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_agent', '0003_agentconfiguration_platformaccount_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='display_name',
            field=models.CharField(default='Agent', max_length=128),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='system_prompt_override',
            field=models.TextField(blank=True, help_text='Override the default system prompt', null=True),
        ),
    ]
